---
# yaml-language-server: $schema=https://raw.githubusercontent.com/steinzi/network-automation-landscape/main/schemas/landscape2-settings-schema.json
# Documentation for this file can be found at:
# https://raw.githubusercontent.com/cncf/landscape2/main/docs/config/settings.yml
# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml


foundation: Network Automation Landscape

url: https://steinzi.com/network-automation-landscape/

base_path: /network-automation-landscape/

colors:
  color1: "rgba(0, 107, 204, 1)"
  color2: "rgba(255, 0, 170, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"



# This let's us provide a hightlighted item in the landscape.
featured_items:
  # By maturity we mean the business model of the software or its current status.
  - field: maturity
    options:
      # Completely open-source software with no restrictions on use, modification, or distribution.
      # Often uses licenses like GPL, MIT, or Apache.
      # Richard Stallman would be proud.
      - value: full-open-source
        order: 1
        label: Full Open Source

      # Open-source software where the core product is free and open, and the vendor
      # offers paid professional support, consulting, or training services.
      - value: oss-with-paid-support
        order: 2
        label: Open Source with Paid Support

      # A business model offering a basic free version with limited features,
      # and a premium paid version with full functionality or advanced features.
      - value: freemium
        order: 3
        label: Freemium (Limited Free Version)

      # Paid software that offers a free trial period, allowing users to test
      # the full product for a limited time before purchasing.
      - value: commercial-with-trial
        order: 4
        label: Commercial with Free Trial

      # Software that is only available through paid licenses, with no free version
      # or trial period available. Users must purchase to use the software.
      - value: commercial-only
        order: 5
        label: Commercial Only

      # Software targeted at large organizations, often with complex pricing structures
      # based on usage, number of users, or custom requirements. May require direct
      # sales contact for pricing and licensing.
      - value: enterprise
        order: 6
        label: Enterprise (Custom Pricing)

      # Cloud-based software offered on a subscription basis. Users pay for access
      # to the software, which is hosted and maintained by the provider.
      - value: saas
        order: 7
        label: Software as a Service

      # A model where the core functionality is open-source, but additional features,
      # tools, or services built around the core are proprietary and paid.
      - value: hybrid
        order: 8
        label: Hybrid (Open Core with Proprietary Extensions)

      # The project shows no recent development activity and is no longer being actively maintained.
      - value: inactive
        order: 9
        label: Inactive/Unmaintained

      # The project is still available but is no longer supported or recommended for use,
      # often because a newer alternative is available.
      - value: deprecated
        order: 10
        label: Deprecated

      # The project has reached the end of its supported lifecycle, has been officially ended,
      # or withdrawn from active development.
      - value: end-of-life
        order: 11
        label: End of Life/Discontinued

      # The project has been placed in a read-only state, is no longer accepting contributions,
      # and is preserved for reference purposes.
      - value: archived
        order: 12
        label: Archived
      
      # The project is closed source, and very restrictive in terms of use, modification, or distribution.
      # Often uses licenses like EULA. (Made just for http://torero.dev)
      - value: free-restrictive
        order: 13
        label: Free restrictive Software

      # A model where the core/framework is closed-source or provided in binary form,
      # but a significant portion (libraries, plugins, extensions) is open-source.
      - value: closed-core
        order: 14
        label: Closed Core (Closed Core with Open Extensions)

footer:
  links:
    # facebook: "https://www.facebook.com/CloudNativeComputingFoundation/"
    # flickr: "https://www.flickr.com/photos/143247548@N03/albums"
    github: "https://github.com/steinzi/network-automation-landscape/"
    # homepage: "https://cncf.io"
    # instagram: "https://www.instagram.com/humans.of.cloudnative/"
    # linkedin: "https://www.linkedin.com/company/cloud-native-computing-foundation/"
    # slack: "https://slack.cncf.io/"
    # twitch: "https://www.twitch.tv/cloudnativefdn"
    # twitter: "https://twitter.com/cloudnativefdn"
    # wechat: "https://www.cncf.io/wechat/"
    # youtube: "https://www.youtube.com/c/cloudnativefdn"
  logo: "https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/white/cncf-white.svg"
  text: |
      Copyright © 2024 STEINZI. Some rights reserved...
      Thanks for helping: Urs Baumann - Mateusz Frąk - Guillaume Mazoyer - Roman Dodin

grid_items_size: small

groups:
  - name: Projects and products
    categories:
      - Network state
      - Telemetry and observability
      - Automation Tooling
      - Security
      - Virtualization
      - Terraform Eco-System
      - Python Eco-System
      - GoLang Eco-System
      - Reporting & Insights
      
  # TODO: make this happen so we can make some groups and be cool like the CNCF landscape.
  # - name: Open Source only
  #   categories:
  #     - Telemetry and observability

header:
  links:
    github: "https://github.com/steinzi/network-automation-landscape/"
  # TODO: put the logo in the logos folder or something.
  logo: "https://raw.githubusercontent.com/steinzi/network-automation-landscape/main/docs/screenshots/logo-black.png"

screenshot_width: 1500
